cloud:
  aws:
    credentials:
      access-key: AKIAQBMNXBVHBWFPQ2UA
      secret-key: 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
    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: myfirstuser

server:
  port: 9090